server {
  listen 80;
  server_name _;
  location /api/ { proxy_pass http://nesgesfinance-backend:3000; proxy_set_header Host $host; }
  location /ws { proxy_pass http://nesgesfinance-backend:3000; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
  location / { proxy_pass http://nesgesfinance-frontend:80; proxy_set_header Host $host; }
}
